# Generated by Django 5.2.2 on 2025-06-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='ManavciUser',
        ),
    ]
