version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    #build: .
    image: manavciapi:latest
    container_name: gin_api_container
    command: ["./main"]
    depends_on:
      - db
    ports:
      - "5001:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 123123
      DB_NAME: postgres
      DB_PORT: 5432
   # volumes:
    #  - ./go-gin-api:/go-gin-api
    restart: always

volumes:
  postgres_data:
